### ISSUE TITLE
Preprocessing details

### ISSUE THREAD

**Issue by bckim92** [shashiongithub/XSum-Dataset#2]
Hello,

We would like to use your dataset, but I cannot find preprocessing details (e.g. tokenization) in your paper.
Can you tell me the details? 

Thank you

**Comment by shashiongithub** [comment]
Sorry, we must have missed it. I used Stanford CoreNLP toolkit to preprocess (segment and tokenize) the extracted dataset. Then, during training and at test time the input document was truncated to 400 tokens and the length of the summary limited to 90 tokens
